### ISSUE TITLE
Match list view should have three views

### ISSUE THREAD

**Issue by maykev** [maykev/shotclockscorekeeper#22]
The match list view should have the ability to show created, in progress and finished matches.

I thought a tab based view would be good.  Not sure what's available in the mobile world, but something along the lines of tabs across the top for these 3 sections.

The purpose of this is to allow matches that were in progress or finished to be restarted.

Let me know if you'd prefer the API /api/matches to return:

{
    created: [...],
    in_progress: [...],
    finished: [...]
}

or 

[
    {
        status: "created",
        ...
    },
    {
        status: "in_progress",
        ...
    },
    {
        status: "finished",
        ...
    }
]

**Comment by ralepinski** [comment]
Do we need finished games? I would prefer the latter with an option to pass in the requested filter as a url param. /api/matches?status=in_progress&tournament=1

**Comment by maykev** [comment]
yeah we need finished.  It's definitely an edge case but there were cases this weekend where they finish a match accidentally.

I like adding a querystring param.  I thought maybe you'd only want to make one call, but if you want to make the call depending on what tab they've selected that then actually works better for me.

I'll make it default to created

/api/matches?tournament=1 - created matches
/api/matches?tournament=1&status=created - created matches
/api/matches?tournament=1&status=in_progress - in progress matches
/api/matches?tournament=1&status=finished - finished matches

The match object will remain unchanged.  Unless adding status to the match object will help?

**Comment by maykev** [comment]
I've deployed this API update to the test sever

**Comment by ralepinski** [comment]
No need for the match object change for now. Pushed change. Fully connected tournaments now have 3 lists.

**Comment by maykev** [comment]
I noticed one issue here and I'm not sure how we should solve it.  If you're re-starting a match that's already in progress then the table that it's using is unavailable for selection.  Do you have access to the table being used for the selected 'in progress' match?  If not I could provide another API that gives you all the tables regardless of whether they're in use or not.  Would be better if we could only allow them to select from the available tables and the one in use for the selected match

**Comment by ralepinski** [comment]
When a match is selected in a list we now add the matches table number if it is in progress
