### ISSUE TITLE
Send score update including final score before match is finished

### ISSUE THREAD

**Issue by maykev** [maykev/shotclockscorekeeper#23]
Right now we don't send the final score until the match is marked as finished.  This results in the live scoring never showing the final score.  It would be good for the final score to be shown until the mark is marked as finished.

So this means when the score is updated to indicate its over a score update should be sent to PUT /api/match with the final score but finished should still be false.

Then when the confirmation of the match being finished is clicked the call with finished: true should be sent

**Comment by ralepinski** [comment]
Do you want a loading dialog before the user is allowed to exit the match?

**Comment by maykev** [comment]
Not necessarily but we do need to ensure the finish request is sent last.  So maybe disable the confirm on the match finished dialog until a response has been received for the last update.  It's not essential that the last score update is successful but we do need the response so that we can ensure the finish update is the last update processed by the server

**Comment by ralepinski** [comment]
Fixed.
