### ISSUE TITLE
Increase font sizes

### ISSUE THREAD

**Issue by maykev** [maykev/shotclockscorekeeper#25]
We have a bunch of old people so the text across the system is too small.  The only screen that doesn't need enlargement is the PlayMatch activity.

Everything else including dialogs should be increased.  The toughest place right now is the table selection

**Comment by ralepinski** [comment]
Can we rely on the system settings to increase font size ? You can make it pretty big. I will need to tweak the play match activity to use DPs instead of SPs so it wont affected. Ill still make a few changes to make things slightly bigger.

**Comment by maykev** [comment]
I can try that, I'll get back to you

**Comment by maykev** [comment]
Increasing the font size on the tablets helped.  The table numbers in the dropdown are still a little on the small side.  They're smaller than the rest of the text for some reason.  As you expected the PlayMatch activity is messed up by doing this

**Comment by ralepinski** [comment]
Pushed a change to increase the table drop down size and use DPs for the play match screen. Let me know if that works.

**Comment by maykev** [comment]
Just need to adjust the shot clock DP to be smaller so the scores have more space in portrait mode and scores a little smaller in landscape mode.  I never could figure out how to stop Android putting so much whitespace around text so it always felt to me like you have to use a smaller font than what can actually fit.
