### ISSUE TITLE
When user quits a match it should set the matches state back to created

### ISSUE THREAD

**Issue by maykev** [maykev/shotclockscorekeeper#26]
Need an modify the PUT /api/match API to allow this.  I propose instead of having finished in the payload we have status which can be 'created', 'in_progress' or 'finished'

**Comment by maykev** [comment]
Deployed this to the test server, but kept it backward compatible for now.

New payload to update a match looks like this: 

status can be "created", "in_progress" or "finished"

{ 
    "table": 2,
    "status":"in_progress",
    "players": [
        {
            "id": 209,
            "score": 2
        },
        {
            "id": 203,
            "score": 5
        }
    ]
}

**Comment by ralepinski** [comment]
Done
