### ISSUE TITLE
Clicking start match fails when web server is down

### ISSUE THREAD

**Issue by maykev** [maykev/shotclockscorekeeper#4]
The app crashes when you click the 'start match' button when the web server is down.  We should handle this gracefully with an error dialog saying that the web server is currently down and please try again

**Comment by ralepinski** [comment]
Do we need to worry about multiple create calls? What if they start creating a game then close the app, reopen and try again? Something to worry about?

**Comment by maykev** [comment]
It's ok for them to create the same match multiple times, but in issue #5 we're going to alleviate this happening unintentionally by clicking the button multiple times (because for some reason people like to double click)
